services:
  db-mysql:
    image: mysql:8.0.33
    env_file:
      - ./docker/mysql/.env
    volumes:
      - db-mysql-volume:/var/lib/mysql
    networks:
      - backend
  # Use custom php-fpm build with all dependecies installed
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./code:/var/www/html
    ports:
      - '9000:9000'
    networks:
      - backend
  web:
    image: nginx:1.25.1-alpine
    ports:
      - '80:80'
    volumes:
      - ./code:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - db-mysql
    networks:
      - backend
volumes:
  db-mysql-volume:
networks:
  backend: